In [1]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.metrics import accuracy_score
import sklearn
import sklearn.datasets
import sklearn.linear_model as l

In [2]:
def read_data(file_name):
    # Read the data with its path location
    try:
        data = pd.read_csv(file_name)
        return data
    except Exception:
        sys.exit(1)

In [3]:
def trainValTestSplit(data):
    shuffled = data.sample(frac=1, random_state=1)
    dataSize = len(shuffled)
    train = shuffled[:int(dataSize * 0.7)]
    val = shuffled[int(dataSize * 0.7):int(dataSize * 0.8)]
    test = shuffled[int(dataSize * 0.8):]
    return train, val, test

In [4]:
def normalize(X, min, max):
    X = (X - min) / (max - min)
    return X

In [34]:
def get_data(file_location):
    data = read_data(file_location)

    train, val, test = trainValTestSplit(data)
    minVal = train.iloc[:, :-1].min()
    maxVal = train.iloc[:, :-1].max()

    X_train = np.array(normalize(train.iloc[:, :-1], minVal, maxVal))
    X_val = np.array(normalize(val.iloc[:, :-1], minVal, maxVal))
    X_test = np.array(normalize(test.iloc[:, :-1], minVal, maxVal))

    y_train = np.array(train.iloc[:, -1:])
    y_val = np.array(val.iloc[:, -1:])
    y_test = np.array(test.iloc[:, -1:])

    return X_train, X_val, X_test, y_train, y_val, y_test

In [35]:
absolutePath = r'C:\Users\gulce\Desktop\EEE 8TH SEMESTER\CS 464\Homeworks\HW2\dataset.csv'
# absolutePath = input('Enter the file location of the dataset: ')
X_train, X_val, X_test, y_train, y_val, y_test = get_data(absolutePath)

In [36]:
print("X_train shape: {}".format(X_train.shape))
print("X_val shape: {}".format(X_val.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_train shape: {}".format(y_train.shape))
print("y_val shape: {}".format(y_val.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (42000, 12)
X_val shape: (6000, 12)
X_test shape: (12000, 12)
y_train shape: (42000, 1)
y_val shape: (6000, 1)
y_test shape: (12000, 1)


In [37]:
clf = l.LogisticRegression()
clf.fit(X_train, y_train)

score = clf.score(X_test, y_test)
print(score)

0.8161666666666667


C:\Users\gulce\anaconda3\envs\LogisticRegression\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [123]:
ones = np.ones((1, X_train.shape[0]))
X_train = np.insert(X_train, 0, ones, axis=1)
print(X_train.shape)
print(X_train)

(42000, 13)
[[1.         0.30956952 0.28367322 ... 0.59995754 0.40000619 0.8800661 ]
 [1.         0.59887455 0.55850998 ... 0.75935779 0.73983466 0.42448846]
 [1.         0.71191971 0.40501184 ... 0.40527032 0.91204029 0.37719168]
 ...
 [1.         0.44895634 0.84187827 ... 0.53344166 0.721973   0.93609452]
 [1.         0.9499972  0.10242888 ... 0.53987897 0.79409739 0.51475455]
 [1.         0.71979276 0.96154749 ... 0.15268457 0.83782957 0.30578468]]


In [124]:
def sigmoid(z):
    s = 1 / (1 + np.exp(-z))
    return s

In [125]:
def gaussianInitialization(dimension):
    w = np.random.normal(loc=0, scale=1, size=(dimension, 1))
    return w

In [126]:
def createBatches(X_train, batchSize):



SyntaxError: incomplete input (2690429108.py, line 3)

In [133]:
class LogisticRegression:
    def __init__(self, epochs=100, learningRate=0.001, batchSize=64):
        self.epochs = epochs
        self.learningRate = learningRate
        self.batchSize = batchSize

    def fit(self, X_train, y_train):
        m = X_train.shape[1]
        w = gaussianInitialization(m)
        for x in range(len(X_train)):
                A = X_train[x].reshape(1, (len(X_train[x])))
                prob = sigmoid(np.dot(A, w))
                dw = np.dot(A.T, (y_train[x]-prob))
                w -= self.learningRate * dw
        return w

    def predict(self, w, X, threshold):
        y_pred = np.zeros(X.shape[0])
        print(w.shape)
        w = w.reshape(X.shape[1], 1)
        print(w.shape)
        A = sigmoid(np.dot(X, w))
        print(A.shape)
        for i in range(A.shape[0]):
            if A[i,0] > threshold:
                y_pred[i] = 1
            else:
                y_pred[i] = 0
        return y_pred

In [134]:
model = LogisticRegression(10, 1)
w = model.fit(X_train, y_train)
print(w)

[[26864.05517725]
 [14811.09048174]
 [14788.41756675]
 [14856.14864805]
 [14843.29551662]
 [13649.48118635]
 [13400.93878795]
 [13362.80685455]
 [13379.21428694]
 [14663.03415493]
 [14714.34704991]
 [14720.69242063]
 [14735.16714024]]


In [135]:
Y_prediction_train = model.predict(w, X_train, 0.5)

(13, 1)
(13, 1)
(42000, 1)


In [136]:
print(Y_prediction_train)
print(Y_prediction_train.shape)

[1. 1. 1. ... 1. 1. 1.]
(42000,)


In [137]:
print(np.count_nonzero(Y_prediction_train))

42000


In [138]:
print(accuracy_score(Y_prediction_train, y_train))

0.36038095238095236
